meter = int(input("meter-"))
decimetre = (meter * 10)
centimeter = (meter * 100)
millimeters = (meter * 1000)
mile = ( meter / 1609 )
print("decimetre-",decimetre)
print("centimeter-",centimeter)
print("millimeters-",millimeters)
print("mile-",mile)